### ISSUE TITLE
packagemap --> modulemap?

### ISSUE THREAD

**Issue by vitalets** [domenic/package-name-maps#25]
For me **modulemap** is more relevant name than **packagemap** because we are talking about *ECMAScript modules*, using `<script type="module" ... >` and usually refer to `/node_modules`.

**Comment by matthewp** [comment]
There's some discussion in other issues about using this outside of JS modules.

**Comment by ljharb** [comment]
Every file is a module; a package is a published directory that might have modules in it.

Bare imports in node, however, always point to a package (or a module within a package).

I’m not sure what the better name is.

**Comment by justinfagnani** [comment]
The reason we chose Package Name Map is because the mapping is primarily concerned with being able to resolve the location of a package name. From there we can resolve paths relative to that location. The proposal hinges on adding the concept of a package - a specific named entity that has a path-based location - that doesn't really exist anywhere in JS or the web platform today.

**Comment by domenic** [comment]
Closing per @justinfagnani's excellent explanation. See also https://github.com/domenic/package-name-maps#supplying-out-of-band-metadata-for-each-module for how this is focused specifically on packages, and not on modules.

**Comment by vitalets** [comment]
Ok, thanks!
