### ISSUE TITLE
Dependencies of Dependencies

### ISSUE THREAD

**Issue by backspaces** [domenic/package-name-maps#26]
This makes sense for an app's direct dependencies.

But what about dependencies the dependencies have, and I have no idea that they are there?

Imagine a npm listing. 
* Depth = 1 are my direct dependencies. OK. My responsibility to map them. 
* Depth > 1 are lurking dependencies I don't know even exist! Who's responsible for their mapping?

I could easily end up with the same package, same version but from different paths!

This is a serious, serious issue ESMs have to deal with. Glad to see it discussed here.

**Comment by ljharb** [comment]
From an npm package, this could be programmatically generated.

**Comment by domenic** [comment]
A key feature of this proposal is that an application needs to be aware of all the code it is executing---or at least, the names of all the packages it is executing. On the web, that is basic security hygiene.

Whether you delegate that responsibility to a tool, or are aware of it yourself, that's up to you. But it's not a design goal of this proposal to allow you to get away with transitive "lurking" dependencies you "don't know even exist". _You_ are responsible for their mapping, because you are the one choosing to include their code in your application.
